import { PropsWithChildren } from 'react';

export default function Head({ children }: PropsWithChildren) {
    return (
        <html>
            <head>
                <title>FixFinity</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </head>
        </html>
    );
}
